euc = read.table("C:/Users/Dawit Tewelde/Desktop/eucalyptus.txt",header = T)
summary(euc)
plot(ht~circ,data = euc)
regeuc = lm(ht~circ,data=euc)
summary(regeuc)
regeuc
attributes(regeuc)
abline(regeuc, col="red")
circ = seq(min(euc[,"circ"]),max(euc[,"circ"]),length=100)
grid = data.frame(circ)
CIpred = predict(regeuc,new=grid,interval = "pred",level = 0.95)
matlines(grid$circ,cbind(CIpred), Ity=c(1,2,2),col=2)

multreg = lm(ht~circ+I(sqrt(circ)),data = euc)
summary(multreg)
plot(ht~circ, data = euc)
circ = seq(min(euc[,"circ"]),max(euc[,"circ"]),length=100)
grid2 = data.frame(circ)
CIpred2 = predict(multreg,new=grid2,interval="pred",level=0.95)
matlines(grid2$circ,cbind(CIpred2),lty = c(1,2,2),col = 2)
win.graph(800,600,10)
plot(regeuc)
plot(multreg)
ozone = read.table("C:/Users/Dawit Tewelde/Desktop/ozone.txt",header = T)
summary(ozone)
win.graph(800,600,10)
pairs(ozone[1:11])
cor(ozone[1:11])
